#--------------------------
#  Global compiler options
#--------------------------

CXX      = g++
WARNINGS = -Wall -Wextra -pedantic -Weffc++ -Werror

# binary name will be directory name
BIN      = popsim


#--------------------------
#  Target-specific compiler options
#--------------------------

FLAGS             = -std=c++0x
release:  FLAGS  += -O3
debug:    FLAGS  += -g -D_DEBUG


#--------------------------
#  Linker
#--------------------------

LIBS      = 

# Uncomment this if using Boost system or thread classes
#LIBS      += -lboost_system-mt -lboost_thread-mt


#--------------------------
#  Source and binaries
#--------------------------

SOURCE  = *.cpp
OBJS    = $(patsubst %.cpp,%.o,$(wildcard $(SOURCE)))
DEPS    = $(OBJS:.o=.d)


#--------------------------
#  Primary target rules
#--------------------------

default: release

.PHONY: release
release: $(BIN)

.PHONY: debug
debug: $(BIN)

.PHONY: clean
clean:
	rm -f $(DEPS)
	rm -f $(OBJS)
	rm -f $(BIN)


#--------------------------
# Autogenerated header dependencies
#--------------------------

-include $(DEPS)


#--------------------------
# Pattern rules
#--------------------------

%.o : %.cpp
	$(CXX) -c $(FLAGS) $(WARNINGS) -MMD -o $@ $<


#--------------------------
# Binary rules
#--------------------------

$(BIN): $(OBJS)
	$(CXX) -o $(BIN) $(OBJS) $(LIBS)
